categories:
  - Groceries
  - Eating Out
  - Transport
  - Shopping
  - Subscriptions
  - Rent
  - Bills
  - Personal Care
  - Fitness
  - Travel
  - Investment
  - Income
  - Transfer
  - Misc
  - Uncategorized
